---
#
# Configuration file for the `htmltest` tool.
# The `htmltest` tool is validating the internal and external links on the HTML build of the documentation.
# See: https://github.com/wjdp/htmltest
#
DirectoryPath: build/site/ # Not build/site to avoid false positives on 404.html
OutputDir: .cache/htmltest
CacheExpires: "12h" # Default is 2 weeks.
ExternalTimeout: 60 # (seconds) default is 15.
IgnoreURLs:
  - https://cse.google.com/cse.js
  - https://github.com/themr0c/antora-for-modular-docs/generate
