---
#
# Antora Playbook for development.
#
# Use this playbook to build current changes not commited yet (git HEAD).
#
# See: https://docs.antora.org/antora/2.3/playbook/
#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

site:
  title: DevWorkspace Operator Documentation
  # url: Disabled on purpose to avoid htmltest crawling the live website.
  start_page: docs::index.adoc
  robots: allow
content:
  sources:
    - url: ./
      branches: HEAD
output:
  clean: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
urls:
  html_extension_style: indexify
  redirect_facility: static
runtime:
  cache_dir: ./.cache/antora
