:_module-type: PROCEDURE

[id="proc_image-pull-secrets_{context}"]
= Image pull secrets

[role="_abstract"]
Image pull secrets can be configured to automatically be added to the devworkspace. In order to do this, you must create a secret in your namespace with the type set to either `kubernetes.io/dockercfg` or `kubernetes.io/dockercfgjson` and the following label applied:

.Labels for configuring image pull secrets
[cols="40,10,10,~"]
|===
|Label |Default| Required| Description

|controller.devfile.io/devworkspace_pullsecret
|None
|yes
|If you want the image pull secret mounted in the namespace. If the label is not specified or if the label is set to false then the image pull secret will not be mounted to the devworkspace
|===

.Procedure

* Define the label `'controller.devfile.io/devworkspace_pullsecret': 'true'` in a secret with the secret type `kubernetes.io/dockercfg` or `kubernetes.io/dockercfgjson`

.Dockerconfig secret
====
[source,yaml]
apiVersion: v1
kind: Secret
metadata:
  name: ${your name}
  namespace: ${your namespace}
  labels:
    'controller.devfile.io/devworkspace_pullsecret': 'true'
type: kubernetes.io/dockercfg
data:
  .dockercfg: ${your docker config}
====

.Dockerconfigjson secret
====
[source,yaml]
apiVersion: v1
kind: Secret
metadata:
  name: ${your name}
  namespace: ${your namespace}
  labels:
    'controller.devfile.io/devworkspace_pullsecret': 'true'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${your docker config json}
====
